export const GET_LIST_PRODUCT_REQUEST = 'GET_LIST_PRODUCT_REQUEST';
export const GET_LIST_PRODUCT_SUCCESS = 'GET_LIST_PRODUCT_SUCCESS';
export const GET_LIST_PRODUCT_FAILED = 'GET_LIST_PRODUCT_FAILED';
