export const CHECK_TOKEN_REQUEST = 'CHECK_TOKEN_REQUEST';
export const CHECK_TOKEN_SUCCESS = 'CHECK_TOKEN_SUCCESS';
export const CHECK_TOKEN_FAILED = 'CHECK_TOKEN_FAILED';
export const NOT_AUTH = 'NOT_AUTH';

export const REDIRECT_LOGIN = 'REDIRECT_LOGIN';

export const SET_AUTHENTICATION = 'SET_AUTHENTICATION';
