export const GET_LIST_PRODUCT_ADMIN_REQUEST = 'GET_LIST_PRODUCT_ADMIN_REQUEST';
export const GET_LIST_PRODUCT_ADMIN_SUCCESS = 'GET_LIST_PRODUCT_ADMIN_SUCCESS';
export const GET_LIST_PRODUCT_ADMIN_FAILED = 'GET_LIST_PRODUCT_ADMIN_FAILED';
export const DELETE_PRODUCT_ADMIN_REQUEST = 'DELETE_PRODUCT_ADMIN_REQUEST';
export const DELETE_PRODUCT_ADMIN_SUCCESS = 'DELETE_PRODUCT_ADMIN_SUCCESS';
export const DELETE_PRODUCT_ADMIN_FAILED = 'DELETE_PRODUCT_ADMIN_FAILED';
