export const GET_PRODUCT_BY_KEYWORD_REQUEST = 'GET_PRODUCT_BY_KEYWORD_REQUEST';
export const GET_PRODUCT_BY_KEYWORD_SUCCESS = 'GET_PRODUCT_BY_KEYWORD_SUCCESS';
export const GET_PRODUCT_BY_KEYWORD_FAILED = 'GET_PRODUCT_BY_KEYWORD_FAILED';
